alias co5="git checkout"
alias ch5="git cherry-pick"
alias cn5="git cherry-pick -n"
alias s5="git status"
alias st5="git stash"
alias sta5="git stash apply"
alias e5="git log"
alias i5="git init && git add . && git commit -m 'initial commit'"
alias d5="git diff"
alias b5="git branch -v"
alias gb5="git branch -v | grep '*'"
alias sh5="git show HEAD"
alias gr5="git grep"
alias rt5="git revert"
alias w5="git pull origin master --rebase"

alias r5="git reset --hard"
alias r25="git reset --hard HEAD~1"
alias r35="git reset --hard HEAD~2"
alias r1005="git reset --hard HEAD~100"

alias re25="git rebase -i HEAD~2"
alias re35="git rebase -i HEAD~3"
alias re45="git rebase -i HEAD~4"
alias re55="git rebase -i HEAD~5"
alias re65="git rebase -i HEAD~6"

alias a5="git commit --amend"
